disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - missing_docs
  - multiline_parameters
  - vertical_whitespace
  - sorted_imports

excluded:
  - .build
  - Pods
  - XCTest
  - GigaRizz.xcodeproj
  - DerivedData

line_length:
  warning: 180
  error: 250

identifier_name:
  min_length: 2
  max_length: 60

force_cast: error
force_try: error

closure_spacing:
  apply_only_to_symbolic_declarations: false
