disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - nesting
  - todo
  - large_tuple
  - trailing_newline
  - cyclomatic_complexity
  - for_where
  - warning_threshold

opt_in_rules:
  - empty_count
  - contains_over_first_not_nil
  - explicit_init
  - fatal_error_message
  - first_where
  - sorted_imports

excluded:
  - .build
  - Pods
  - XCTest
  - GigaRizz.xcodeproj
  - DerivedData
  - Package.swift
  - GigaRizz/Package.swift

identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - i
    - j
    - k
    - m
    - n
    - p
    - x
    - y
    - id
    - a

force_cast: error
force_try: error
